### ISSUE TITLE
ConcurrentModificationException within CookAgent

### ISSUE THREAD

**Issue by ghost** [usc-csci201-fall2013/restaurant#10]
I'm getting intermittent ConcurrentModificationException errors within the CookAgent class. This is causing my program to crash due to heap memory being full. I know we shouldn't worry about this for v2, but I'd still like to report it as an issue, mostly because I can't really seem to test out all the scenarios for my Restaurant.

**Comment by lee533** [comment]
A quick fix that doesn't really address the problem is changing all "for each" loops to normal for loops. For example, change:
for (Order o : orders)
to:
for (int i = 0; i < orders.size(); i++)
While this doesn't fix the underlying issues, it prevents Java from showing the ConcurrentModificationException errors (which come from using Iterators, which the "for each" loops compile to).

The heap error may be something different; check for infinite loops (see issue #6).

**Comment by janicejl** [comment]
#6
