### ISSUE TITLE
Images Loading When First Downloaded From Git

### ISSUE THREAD

**Issue by lshiffer** [usc-csci201-fall2013/restaurant#18]
None of my images load when I first download from GitHub until I move them to Eclipse's workspace.  Is there a way to code the filepath so it can pull the images from the downloaded src file?

Thanks.

**Comment by alghanmi** [comment]
This topic has been asked in multiple issues, I will discuss it here since this issue has the clearest title. Other issues such as #17, #16, #13 should refer to this answer.

**Bottom line**: you should provide instructions that will make your code work on the grader's machine.

There are two ways to refer to files, using:
- **Relative Paths**: in which you provide a path to a file using a link relative to a know location, e.g. `images/myimage.png`. Think of it like when you make a hyperlink in a web page and you use the file name without including the domain name.
- **Absolute Path**: that is you include the full path of the file on your storage device, e.g.
  - `/home/ttrojan/projects/cs201/restaurant_ttrojan/images/myimage.png`, or
  - `C:/Users/TTrojan/Desktop/cs201/restaurant_ttrojan/images/myimage.png`

Generally speaking, when using absolute paths, you are almost guaranteed that your code will only properly work on **your private** machine. Therefore you are expected to use **relative paths**.

A number of problems arise when using relative paths including copying your files to the `bin` or `build` directories. I found these to be "hacks" and not a real solution to the problem.

Here I am proposing a solution that should work for you and also make it possible to run your application from the commandline without the need to eclipse which in my book is a huge plus!!!

**Step 1**: Create a directory in your eclipse project for all your images. Lets call it `images`.

**Step 2**: Copy **all** your image files there.

![selection_002](https://f.cloud.github.com/assets/348553/1234510/96530132-297a-11e3-90c0-0a6ae9d69bb0.png)

> Eclipse project with images directory and a file named `baracktocat.jpg`

**Step 3**: Right click on your Eclipse Project and select **Refresh**

**Step 4**: Right click on your `images` directory and select **Buid Path** :arrow_right: **Use as a Source Folder**

That is it! Now, you should refer to all your images using the relative path `images/baracktocat.jpg`. Just make sure you add the images directory to your GitHub repo.

Misc Issues:
1. You are not to submit any compiled files to packages of any sort. Pushing such files to your repo will cause you to get penalized.

**Comment by waynchi** [comment]
I found a solution to this problem!

First of all, when you create your new ImageIcon(this.getClass().getResource(<Filename and location from where this class is located>).
This will allow you to use files inside your build folder. However, since the build folder will not download from github/work with the current ant build, you need to actually edit the Build.xml File.

Inside the file, there is a section that is commented out that helps copy code over to the build file (I have no idea why this is commented out.) Uncomment it and add whatever extension you want e.g. jpg

**Comment by lshiffer** [comment]
Would it be acceptable to simply drop all items into an Image folder and request grader drag the folder into his/her Eclipse workspace?

**Comment by lshiffer** [comment]
The above solution isn't working.  

I followed the steps of creating an Image directory and filling it up and having it be a source folder, and when I downloaded the Images folder came with but nothing is loading still.

**Comment by alghanmi** [comment]
If you re-cloned and/or re-imported the project, you need add the directory again to your build path.

**Comment by ravis411** [comment]
Hi Rami, I know this issue already has some answers but we can't seem to get it to work. I can add images to Eclipse and use the relative path like you described above however, the images do not get added to git. Also, when I put the images folder in git I cannot seem to use the relative path to reference them. Could someone post some clearer instructions on how to add images to git, and make them load in the project using Eclipse or however someone runs the project. Google was no help either. Thank you. How do we add images so that someone else running our project does not have to do anything to make the images load?
