### ISSUE TITLE
Order as a Regular Class

### ISSUE THREAD

**Issue by lshiffer** [usc-csci201-fall2013/restaurant#19]
I currently have Order as a stand-alone class that is instantiated in Waiter when Customer passes his choice (string) to the Waiter.

Waiter then passes Order to the Cook who passes it back when finished.

Is that not acceptable?  Both Waiter and Cook can benefit from the use of Order class.  And if Order is Inner Class in Cook, how do we pass Customer's choice?  One of the emails mentioned only passing Agent pointer...

**Comment by waynchi** [comment]
You closed this, does this mean you've gotten an answer? If you did, I would like to know, thanks.

**Comment by dwilczyn** [comment]
In principle, the Order class as she defined is ok. However, it brings up the issue of sharing data and the need for making deep copies. I did NOT want you to do this right now; that's why I designed the message with primitive int and string. It won't affect your v2 grading. We'll accept it. We will talk about this again in class.

Prof. W.

**Comment by waynchi** [comment]
Ok! Thank you!
