### ISSUE TITLE
Market-Cook Questions

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#32]
I have a couple questions about the design of the market-cook scenario:

1) How do we decide the starting inventory of the markets? Is it randomly generated when we start the program? Do markets get replenished mid-program?

2) How many markets should their be? 

3) To update the cook inventory, do we have to make a whole message-scheduler-action routine, or can we update our inventory right when we get the message from the market?

**Comment by dwilczyn** [comment]
> 1) How do we decide the starting inventory of the markets? Is it randomly generated when we start the program? Do markets get replenished mid-program?

You decide what the inventory should be. Remember you want to be able to test situations where the market CANNOT fulfill an order. And, because of this, the markets DO NOT get replenished; they simply run out.

> 2) How many markets should their be?

I think 3 should do it.

> 3) To update the cook inventory, do we have to make a whole message-scheduler-action routine, or can we update our inventory right when we get the message from the market?

For now, you can do the update in the market message. For v2.2 (or maybe the team project), you will have to animate the update, so you will need scheduler and actions.
