### ISSUE TITLE
Clarificiation of Requirements for Scenarios

### ISSUE THREAD

**Issue by FluffySheep** [usc-csci201-fall2013/restaurant#41]
Hello viewer,

During the labs, we were checked  off for having completed parts of v2.1 such as implementing a waiter going on break and implementing the cashier / customer interaction by following the instructions given at the time.

Thew v2.1 assignment page was just updated recently and contains more detailed paragraphs regarding how each interaction should work. Some of these details contradict what some students have turned in during lab. 

For example, the initial interaction for waiter's going on break is as follows:
1. The waiter has a GUI button for going on a break.
2. When the button is pushed, the waiter does ... what? [We'll talk about the design in class.]
3. What role does the host play? [We'll talk about the design in class.]

Now I added a GUI button for going on break which has the waiter tell the host that waiter is requesting a break. The host puts that waiter in a list of waiters waiting to go on break and notifies the waiter when he is allowed to take a break. Then the waiter returns after a certain amount of time on his own. This seemed to fit the original requirements of the assignment listed for lab and the graders did not ask me to change my design.

The added assignment description now asks us to be able to manually take a waiter off break and allow the host to deny a waiter a break period. Now this example of the waiter going on break scenario is just one of the three changes to the assignment details.

Do we need to change the design documentation and implementation we had approved during lab to meet the recent additions to the new assignment? If so, will there be any more changes to the assignment before the due date on Sunday?

Thank you for your time,
Brian Chen

**Comment by Valakor** [comment]
I would also like clarification on these issues. I too spent many hours completing most of V2.1 for Lab 7 using the requirements set in the issues in our repos and the requirements seen for Lab 7, etc. However, now certain parts of my code do not follow the requirements set in the rubric despite being approved earlier this week.

Here are three examples of issues I have with the new requirements:
1. My Waiters return from break after some set amount of time (say 10 seconds) because I decided this made more sense (they shouldn't be able to sit on break forever). This interaction was left up to us previously without any specific instructions on what we should or should not do; however, now we must leave waiters on break until we manually take them off break through the GUI?
2. My market has a single message that it ever sends to the Cook. After receiving an order from the Cook, after some amount of time (say 8 seconds) this message (orderFulfilled) is sent with the amount the market was able to fulfill, whether or not it was able to fulfill the entire order. My Cook then decides based on the amount received (and the amount he originally ordered) whether he should ask a new market the next time, whether the order was fulfilled, or whether he received nothing and should order more. However now we must send a separate message to the cook from the market immediately upon receiving an order that cannot be completely fulfilled?
3. For the interaction between waiter and cashier when the customer cannot pay his bill, I had already begun implementing a simple blacklist; that is, if a customer cannot pay he is forbidden from returning from the restaurant. Apparently we must instead remember the customer and allow him to pay next time? This seems unnecessarily complex; furthermore, where does he get more money from if he is out?

Clarification on these issues would be greatly appreciated.

@crowley1958

**Comment by khupka** [comment]
I have also implemented mine differently... Are the recently added descriptions suggestions for people who have not completed these parts yet? There was nothing in the grading rubric about them being actual requirements.

**Comment by xli438** [comment]
Yes, the thing that makes me confused is that the rubric didn't mention anything about waiter button design. I also designed the waiter goes on break himself for maybe 10 seconds and goes back automatically. I did the design before those newly posted requirements. Will we consider the button design extra credits since rubric didn't mention that? @alghanmi @mahdiazmandian

**Comment by crowley1958** [comment]
Given that the rubric was posted so late into the assignment, you will not be penalized for implementing your work with a timer.

@alghanmi  Please take note of this in the grading.

**Comment by FluffySheep** [comment]
Thank you.
