### ISSUE TITLE
Restaurant (GUI and Agents) freeze when window focus changes

### ISSUE THREAD

**Issue by johngtimms** [usc-csci201-fall2013/restaurant#45]
If I change window focus (such as clicking back to Eclipse) the GUI and Agents of the restaurant will freeze shortly thereafter. All agents do not freeze at once- one freezes, then the next, then the next, and so on. I have tested my program extensively and run the program for many cycles without changing window focus- in that case, everything works. Things only freeze when the window focus changes. Has anyone else had this problem?

**Comment by jaredborner** [comment]
So here's what's happening. When you call repaint() from the timer's actionPerformed() it does not necessarily call the paintComponent() method. What repaint() really does is make a "suggestion" to the repaint manager/OS. Now if the repaint manager/OS sees that part/all of your window is hidden then it may defer the paintComponent() call until later (because repainting a hidden window would be pointless from its perspective). Since your code to update position is also in the paintComponent() call, it gets deferred as well.
