### ISSUE TITLE
V2.1 Non-norms

### ISSUE THREAD

**Issue by vikrantsinghal** [usc-csci201-fall2013/restaurant#47]
The non-normative scenarios allow the customer to order even though he has less money. But the specifications also indicate that the customer WILL order only the cheapest item on the menu.
The way I have implemented is that the customer can manually choose the item from a list that appears on the infoPanel. When he has less money to buy anything, the leave button appears as well. But in all other cases, the list does appear on the screen without the leave button. The same thing happens if the customer has to reorder. In other words, I have some flexibility in the sense that it is up to the customer if he wants to leave or order even if he's a broke. So is that okay?

**Comment by vikrantsinghal** [comment]
Bump.

**Comment by kevin92805** [comment]
Well the biggest thing is that do you have non-norms to account for both? Some kind of response needs to happen for both situations. Whether its the customer leaving and thus clearing the table or something happens to the customer after he's done eating because he can't pay for the meal. If you cover both those bases, you'll be fine.

**Comment by vikrantsinghal** [comment]
As specified in the rubric, I do have things like paying for it the next time he comes in. So hopefully, I'm good! Thanks a lot!
