### ISSUE TITLE
Checks and when the Waiter hands em over

### ISSUE THREAD

**Issue by Seioch** [usc-csci201-fall2013/restaurant#51]
Heya!

I'm confused on how the waiter should handle checking for the customer. Currently my interaction diagram goes as follows:

customer orders valid food -> Waiter takes the order and creates a new order() -> waiter writes a receipt and immediately hands the receipt to the customer -> does cooking-> customer eats -> Customer runs up to the cashier and hands his receipt to the cashier -> cashier parses the receipt

From this requirement: 

Cashier agent (10 points)
(2 points) Receives order from waiter at some point
(2 points) Creates check
(2 points) Gives the waiter the check upon request.
(2 points) Lets customer pay the next time he comes to the restaurant.
(2 points) Receives money from the customer.

It seems that the <b><i>waiter </b></i> has to give the order to the cashier to do the checking and then bring the recepit back to the customer at some point. I feel that my current Interaction is also valid and conforms to restaurant activity in real life. Should I change this or can I keep it as it is?

**Comment by Seioch** [comment]
Also, another question: My restaurant rarely starts to hang up when I start adding a couple dozen hungry customers and a few waiters. Will that be counted against me?

**Comment by Seioch** [comment]
Bump

**Comment by kevin92805** [comment]
It would be in your best interest to do it the way the rubric states simply because that is how the CPs will be grading your assignment. You may be able to argue for the points back through your reasoning, but you'd have to go through that process. We can't consider each project individually since there's a lot to keep track of so we go off of the rubric.

Regarding your second question you should try to see what the error is if possible. It's hard to tell whether or not a CP will stress test your project and ding you for a deduction due to it crashing because it depends on if it occurs during our tests or not.
