### ISSUE TITLE
Heap Memory Problems

### ISSUE THREAD

**Issue by danielhw** [usc-csci201-fall2013/restaurant#6]
After running a few simulations with different numbers of customers and waiters I seem to always get a java.lang.OutofMemoryError: Java heap space. I have no idea why since it seems to happen even when I've only added 1 or 2 customers and waiters.

**Comment by khupka** [comment]
I had that same problem. Check to see if you are checking a loop constantly when you don't need too. For me, my animation slowed down when that was happening which was the problem. Hope that helps.

**Comment by janicejl** [comment]
There are two reasons that this will typically happen. Hopefully this will be a guideline to let you know where the problem may be. 

1) Inside the animation loop. Since the animation is called over and over again continuously, if you are creating new variables in your loop, you will be using all the memory available to you. 
2) Your scheduler is not well defined and calls actions multiple times. 

Hopefully this solves your heap problem/concurrent modification exception.
