### ISSUE TITLE
V2.2: Cashier-Market Scenario 2

### ISSUE THREAD

**Issue by vikrantsinghal** [usc-csci201-fall2013/restaurant#66]
"One order, fulfilled by TWO markets, 2 bills paid in full."
What does this mean? The cook only requests one market at a time, and he asks another market for the same thing only if the first market cannot give anything to the cook. So only one market can fulfill an order, and only one bill can be generated for an order.

**Comment by vikrantsinghal** [comment]
And also, my implementation doesn't care if the market(s) request the cashier to pay n number of bills (where n >= 1). If there is a pending bill, the cashier will pay it if he has sufficient money.

**Comment by meldefon** [comment]
Just out of curiosity, where does that quote come from? I haven't been able to find the requirements in detail for v2.2

**Comment by vikrantsinghal** [comment]
http://www-scf.usc.edu/~csci201/assignments/rubric03.html
It's the second point under Milestone V2.2A.

**Comment by meldefon** [comment]
Thank you!

**Comment by vikrantsinghal** [comment]
Bump.

**Comment by gregypooh** [comment]
Here's what I assume this requirement means:

This is just a continuation of a v2.1 scenario. 
Market-X cannot completely for-fill an order...
So the cook orders the items that cannot be for-filled by market-X from market-Y.
The point is to have the cashier receive two bills from two separate markets: market-X and market-Y. 

So I think you are right when you say, 
"only one market can fulfill an order, and only one bill can be generated for an order" 
because in this case there are technically two orders being placed.

Somebody correct me if my assumption is wrong!
=)

**Comment by vikrantsinghal** [comment]
I see what you mean. Yeah, that makes sense! Thanks a lot! :)
