### ISSUE TITLE
Unit testing scenarios for the cashier

### ISSUE THREAD

**Issue by gabelew** [usc-csci201-fall2013/restaurant#71]
This part of the requirement confused me: "They should, of course, involve the customer and waiter in v2.1 scenarios, but they should also allow interleaving of market activities during customer/waiter activities."

What does it mean for the interleaving of market activities? Does that mean a reordering scenario from the market? Although I am unsure how that would affect the cashier.

**Comment by gregypooh** [comment]
An example scenario of this would be:
Waiter asks the cashier to compute a customer's check.
Then a market sends a bill to the cashier sometime before the customer pays their check.

I think "market activities" would be better phrased as, "market interactions."

One more thing - the reordering scenario DOES affect the cashier because the cashier will receive two bills instead of one. ;)

**Comment by xulander** [comment]
Is there a specific list of tests they want us to accomplish? Or do we just write as many tests as possible?

**Comment by jakelow** [comment]
the point of the tests are to convince yourself and the grader that every aspect of your agent functionality works correctly. you need to make sure states, variables, and items to be added to lists are being dealt with correctly upon message reception, actions are correctly being called in the scheduler, and the correct messages are being sent to your mock agents. go through every scenario your program handles and see what needs to happen within each agent to make that scenario happen, and explicitly test those things.
