### ISSUE TITLE
Another Synchronization Issue

### ISSUE THREAD

**Issue by vikrantsinghal** [usc-csci201-fall2013/restaurant#76]
I have a MyCheck object in Cashier that stores checks and has various other things, analogous to the MyCustomer data structure in waiter (I have a list called "checks" that stores MyCheck objects). So, my scheduler picks up a check that is being paid through a READ-ONLY operation and calls an action which goes like this:
public void decideResponseForCheck(MyCheck mc) {..}
Inside the action body, I'm not iterating through the list. So, inside the action body, should I put something like "synchronized (mc) {..}"? Because I'm not modifying the list here, I'm just separately modifying a memory location that happens to be a part of the list. Also, if some other thread modifies "checks" at the same time (but a DIFFERENT MyCheck object than "mc"), when "mc" is being modified, will I get the ConcurrentModificationException (considering my previous argument), using the implementation that I have suggested?

**Comment by vikrantsinghal** [comment]
Bump.

**Comment by guehochoi** [comment]
there is no reply here, so im commenting what I think. im am not cp or ta, just student.

since mc is not a list, synchronized(mc) seems like not an issue what we dealt in class. 
however, you do not need to synchronized it in action if you are not iterating through list. You should already synchronized it in scheduler. action is a subroutine of scheduler, not a different thread, threfore, scheduler and action cannot be concurrent. this means that you wont need ti synchronize mc again because it is synchronized already.
just make sure your message is also synced because it is probably where another thread tries to change mc. 
my understanding might not be perfect, please correct me if I am wrong. 
good luck with assignment

**Comment by vikrantsinghal** [comment]
Thanks! Kind of makes sense. I'll try to look into more, keeping in mind what you said! And good luck to you too.

**Comment by Valakor** [comment]
Using a synchronized block is unnecessary unless you are iterating over a list of objects that may change. Simply declaring the list as Collections.SynchronizedList makes specific action calls on the list thread-safe: `myList.add(something)` is thread-safe if myList was declared as `Collections.synchronizedList(new ArrayList())`. However, if you iterate over the list in a message, you should still have a synchronized block.

**Comment by vikrantsinghal** [comment]
Thank you!
