### ISSUE TITLE
Program Freezing Once synchronized() blocks were added

### ISSUE THREAD

**Issue by jlazzaridean** [usc-csci201-fall2013/restaurant#95]
My code was not throwing ConcurrentModificationExceptions as of v2.1, but I've been adding synchronized lists and try/catch blocks for v2.2. Once I started doing this, the program freezes sometimes and won't restart. I think that the problem is in the CookAgent, because it seems to happen whenever the animated cook is plating an order. Has anyone encountered similar issues, and do you know what might be causing them?

**Comment by Valakor** [comment]
Maybe it's not the same problem, but for me if I ever tried to acquire a semaphore from inside a timer's actionListener the program would freeze.
For example, my customers have a function called DoLeaveRestaurant that causes them to animate out of the restaurant. Originally, this function was called when my "waiting" timer was done (the customer waited too long and decided to leave the restaurant). Trying to acquire the semaphore in a method call that occurred because of the timer kept freezing my program, as the timer is technically a separate thread from the agent itself. 
Maybe you're having the same problem?

**Comment by jlazzaridean** [comment]
yeah I think it was a related problem. I switched to using a try/catch block instead of synchronized() for the cook and it seems to have solved the problem. closed #95.
