### ISSUE TITLE
Image Files

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/restaurant#99]
How do we ensure that the grader will be able to access our image files?

**Comment by EliteSoba** [comment]
Go onto a computer at SAL and clone your GitHub repository onto there. If you run it and see your images, then you're good.

If not, make sure your image files are located in your GitHub repository and make sure your references to them are not statically hardcoded in ("img\waiter.jpg" rather than "C:\Users\Tobias\workspace\restaurant\img\waiter.jpg")

**Comment by jdgreenberger** [comment]
I cloned my repository at a computer at SAL. Somehow, the images aren't showing up when I run the program. I know that the eclipse project imports my Image folder and I'm sure they are in a relative file because I declare ("Images/fridge.jpg"), where fridge.jpg is the name of my file.

Any suggestions?

**Comment by alghanmi** [comment]
https://github.com/usc-csci201-fall2013/restaurant/issues/18#issuecomment-25335238

**Comment by jdgreenberger** [comment]
Even when I add Images as a source folder, the images won't load. I tried to edit the build file like mentioned in #18  comments but I can't get it to work.
